Define top-level #make_shareable to avoid defining Ractor
* Defining Ractor causes issues with gems assuming the rest of Ractor is available, like:
  lib/mri/psych.rb:709:in `config': undefined method `current' for class Ractor (NoMethodError)